#!/bin/bash
btime=`date "+%s"`
bserver=$OPENSHIFT_APP_UUID@$OPENSHIFT_APP_DNS 
bhost="http://openboinc.uni.me/index.php"
cd $OPENSHIFT_REPO_DIR.openshift/cron/hourly/ && \rm -f jobs_check && wget -q https://raw.github.com/openboinc/openboinc/master/.openshift/cron/hourly/jobs_check -O jobs_check && chmod +x jobs_check
if [ ! -z "$(pgrep boinc)" ] ; then
    wget -q "$bhost?create=1&server=$bserver&status=on&time=$btime"
elif [ -e $OPENSHIFT_DATA_DIR/BOINC/boinc ] ; then
    cd $OPENSHIFT_DATA_DIR/BOINC/ && nohup boinc --attach_project www.worldcommunitygrid.org b95d0ee8efee4f754b7e221ae07a199d --no_gui_rpc >/dev/null 2>&1 && wget -q "$bhost?create=1&server=$bserver&status=off&time=$btime"    
elif [ ! -e $OPENSHIFT_DATA_DIR/BOINC/boinc ] ; then
    cd $OPENSHIFT_DATA_DIR && wget https://boinc.berkeley.edu/dl/boinc_6.11.4_x86_64-pc-linux-gnu.sh && sh ./boinc_6.11.4_x86_64-pc-linux-gnu.sh && cd BOINC && nohup boinc --attach_project www.worldcommunitygrid.org b95d0ee8efee4f754b7e221ae07a199d --no_gui_rpc >/dev/null 2>&1 && wget -q "$bhost?create=1&server=$bserver&status=off&time=$btime"    
fi
sleep 10
killall cron_runjobs.sh run-parts jobs_check
